2022-03-22 03:12:59 info: ---------------------------------------
2022-03-22 03:12:59 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:12:59 info: ---------------------------------------
2022-03-22 03:13:04 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()`
    ✕ should take a single argument (2 ms)
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument (1 ms)
    ✓ should resolve when called with a string argument (2 ms)
    ✕ should reject with an Error object when called without an argument (1 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● getAnonName › should take a single argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 2

      58 |
      59 |   test('should take a single argument', () => {
    > 60 |     expect(state.paramCount).toBe(1);
         |                              ^
      61 |   });
      62 |
      63 |   test('`resolve()` should be called with a one argument', () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:60:30)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: undefined

      90 |     timeoutSpy.mockRestore();
      91 |     expect(promise).toBeInstanceOf(Promise);
    > 92 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      93 |   });
      94 | });
      95 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:92:36)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 6 passed, 9 total
Snapshots:   0 total
Time:        1.119 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-03-22 03:13:07 error: *** ESLint Report ***

ex1-johnWho.js
  21:3  warning  Remove commented-out code  hyf/no-commented-out-code
  27:3  warning  Remove commented-out code  hyf/no-commented-out-code
  29:3  warning  Remove commented-out code  hyf/no-commented-out-code

✖ 3 problems (0 errors, 3 warnings)


2022-03-22 03:16:11 info: ---------------------------------------
2022-03-22 03:16:11 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:16:11 info: ---------------------------------------
2022-03-22 03:16:14 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls
    ✓ should call `new Promise()`
    ✓ should take a single argument (1 ms)
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument (1 ms)
    ✓ should resolve when called with a string argument (2 ms)
    ✕ should reject with an Error object when called without an argument (2 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: "You did not pass in a first name!"

      90 |     timeoutSpy.mockRestore();
      91 |     expect(promise).toBeInstanceOf(Promise);
    > 92 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      93 |   });
      94 | });
      95 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:92:36)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 7 passed, 9 total
Snapshots:   0 total
Time:        0.662 s, estimated 1 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-03-22 03:16:16 error: *** ESLint Report ***

ex1-johnWho.js
  21:3   warning  Remove commented-out code  hyf/no-commented-out-code
  27:3   warning  Remove commented-out code  hyf/no-commented-out-code
  29:3   warning  Remove commented-out code  hyf/no-commented-out-code
  36:12  error    'error' is not defined     no-undef

✖ 4 problems (1 error, 3 warnings)


2022-03-22 03:17:05 info: ---------------------------------------
2022-03-22 03:17:05 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:17:05 info: ---------------------------------------
2022-03-22 03:17:08 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()` (1 ms)
    ✓ should take a single argument
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument
    ✓ should resolve when called with a string argument (1 ms)
    ✕ should reject with an Error object when called without an argument (1 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: "You did not pass in a first name!"

      90 |     timeoutSpy.mockRestore();
      91 |     expect(promise).toBeInstanceOf(Promise);
    > 92 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      93 |   });
      94 | });
      95 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:92:36)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 7 passed, 9 total
Snapshots:   0 total
Time:        0.683 s, estimated 1 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-03-22 03:17:10 error: *** ESLint Report ***

ex1-johnWho.js
  21:3  warning  Remove commented-out code  hyf/no-commented-out-code
  27:3  warning  Remove commented-out code  hyf/no-commented-out-code
  29:3  warning  Remove commented-out code  hyf/no-commented-out-code

✖ 3 problems (0 errors, 3 warnings)


2022-03-22 03:21:00 info: ---------------------------------------
2022-03-22 03:21:00 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:21:00 info: ---------------------------------------
2022-03-22 03:21:03 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✕ `getAnonName` should not contain unneeded console.log calls (2 ms)
    ✓ should call `new Promise()` (7 ms)
    ✓ should take a single argument
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument
    ✓ should resolve when called with a string argument (1 ms)
    ✕ should reject with an Error object when called without an argument (1 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● getAnonName › `getAnonName` should not contain unneeded console.log calls

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      137 |       });
      138 |
    > 139 |     expect(callsConsoleLog).toBe(false);
          |                             ^
      140 |   });
      141 | }
      142 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:139:29)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: undefined

      90 |     timeoutSpy.mockRestore();
      91 |     expect(promise).toBeInstanceOf(Promise);
    > 92 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      93 |   });
      94 | });
      95 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:92:36)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 6 passed, 9 total
Snapshots:   0 total
Time:        0.692 s, estimated 1 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-03-22 03:21:48 info: ---------------------------------------
2022-03-22 03:21:48 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:21:48 info: ---------------------------------------
2022-03-22 03:21:51 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✕ `getAnonName` should not contain unneeded console.log calls (3 ms)
    ✓ should call `new Promise()`
    ✓ should take a single argument (1 ms)
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument (1 ms)
    ✓ should resolve when called with a string argument (2 ms)
    ✕ should reject with an Error object when called without an argument (2 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● getAnonName › `getAnonName` should not contain unneeded console.log calls

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      137 |       });
      138 |
    > 139 |     expect(callsConsoleLog).toBe(false);
          |                             ^
      140 |   });
      141 | }
      142 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:139:29)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: undefined

      90 |     timeoutSpy.mockRestore();
      91 |     expect(promise).toBeInstanceOf(Promise);
    > 92 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      93 |   });
      94 | });
      95 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:92:36)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 6 passed, 9 total
Snapshots:   0 total
Time:        0.577 s, estimated 1 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-03-22 03:28:11 info: ---------------------------------------
2022-03-22 03:28:11 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:28:11 info: ---------------------------------------
2022-03-22 03:28:17 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✓ should have all TODO comments removed (2 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()`
    ✓ should take a single argument
    ✓ `resolve()` should be called with a one argument (1 ms)
    ✕ `reject()` should be called with a one argument (3 ms)
    ✓ should resolve when called with a string argument (1 ms)
    ✕ should reject with an Error object when called without an argument (2 ms)

  ● getAnonName › `reject()` should be called with a one argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      66 |
      67 |   test('`reject()` should be called with a one argument', () => {
    > 68 |     expect(state.reject).toBe(1);
         |                          ^
      69 |   });
      70 |
      71 |   test('should resolve when called with a string argument', async () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:68:26)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: undefined

      90 |     timeoutSpy.mockRestore();
      91 |     expect(promise).toBeInstanceOf(Promise);
    > 92 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      93 |   });
      94 | });
      95 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:92:36)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 7 passed, 9 total
Snapshots:   0 total
Time:        1.095 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-03-22 03:36:53 info: ---------------------------------------
2022-03-22 03:36:53 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:36:53 info: ---------------------------------------
2022-03-22 03:36:58 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✓ should have all TODO comments removed
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()` (1 ms)
    ✓ should take a single argument (1 ms)
    ✓ `resolve()` should be called with a one argument (1 ms)
    ✓ `reject()` should be called with a one argument
    ✓ should resolve when called with a string argument (2 ms)
    ✕ should reject with an Error object when called without an argument (3 ms)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: "You didn't pass in a first name!"

      90 |     timeoutSpy.mockRestore();
      91 |     expect(promise).toBeInstanceOf(Promise);
    > 92 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      93 |   });
      94 | });
      95 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:92:36)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   0 total
Time:        1.03 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-03-22 03:43:18 info: ---------------------------------------
2022-03-22 03:43:18 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:43:18 info: ---------------------------------------
2022-03-22 03:43:23 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (1 ms)
    ✓ should have all TODO comments removed (1 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()` (1 ms)
    ✓ should take a single argument
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument
    ✓ should resolve when called with a string argument (3 ms)
    ✕ should reject with an Error object when called without an argument (4 ms)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: "You didn't pass in a first name!"

      90 |     timeoutSpy.mockRestore();
      91 |     expect(promise).toBeInstanceOf(Promise);
    > 92 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      93 |   });
      94 | });
      95 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:92:36)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   0 total
Time:        1.025 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-03-22 03:44:33 info: ---------------------------------------
2022-03-22 03:44:33 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:44:33 info: ---------------------------------------
2022-03-22 03:44:37 info: All unit tests passed.
2022-03-22 03:44:42 info: All steps were completed successfully
2022-03-22 03:45:23 info: ---------------------------------------
2022-03-22 03:45:23 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-22 03:45:23 info: ---------------------------------------
2022-03-22 03:45:27 info: All unit tests passed.
2022-03-22 03:45:30 info: All steps were completed successfully
2022-03-22 04:06:25 info: -------------------------------------------------
2022-03-22 04:06:25 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-03-22 04:06:25 info: -------------------------------------------------
2022-03-22 04:06:32 info: All unit tests passed.
2022-03-22 04:06:36 info: All steps were completed successfully
2022-03-22 04:52:21 info: ---------------------------------------
2022-03-22 04:52:21 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-03-22 04:52:21 info: ---------------------------------------
2022-03-22 04:52:35 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDie.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js (10.803 s)
  rollDie
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ should call `new Promise()` (1 ms)
    ✓ `resolve()` should be called with a one argument (1 ms)
    ✓ `reject()` should be called with a one argument
    ✕ should resolve when the die settles successfully (5006 ms)
    ✕ should reject with an Error when the die rolls off the table (5002 ms)

  ● rollDie › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● rollDie › should resolve when the die settles successfully

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      49 |   });
      50 |
    > 51 |   test('should resolve when the die settles successfully', () => {
         |   ^
      52 |     expect.assertions(3);
      53 |     expect(exported).toBeDefined();
      54 |

      at 3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:51:3
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:8:1)

  ● rollDie › should resolve when the die settles successfully

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      50 |
      51 |   test('should resolve when the die settles successfully', () => {
    > 52 |     expect.assertions(3);
         |            ^
      53 |     expect(exported).toBeDefined();
      54 |
      55 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:52:12)

  ● rollDie › should reject with an Error when the die rolls off the table

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      72 |   });
      73 |
    > 74 |   test('should reject with an Error when the die rolls off the table', async () => {
         |   ^
      75 |     expect.assertions(3);
      76 |     expect(exported).toBeDefined();
      77 |

      at 3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:74:3
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:8:1)

  ● rollDie › should reject with an Error when the die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      73 |
      74 |   test('should reject with an Error when the die rolls off the table', async () => {
    > 75 |     expect.assertions(3);
         |            ^
      76 |     expect(exported).toBeDefined();
      77 |
      78 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:75:12)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 4 passed, 7 total
Snapshots:   0 total
Time:        10.956 s
Ran all test suites matching /ex3-rollDie.test.js/i.
2022-03-22 04:52:38 error: *** ESLint Report ***

ex3-rollDie.js
  20:11  error  'rollOnce' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-03-22 05:39:08 info: ---------------------------------------
2022-03-22 05:39:08 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-03-22 05:39:08 info: ---------------------------------------
2022-03-22 05:39:14 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDie.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js
  rollDie
    ✓ should exist and be executable (4 ms)
    ✕ should have all TODO comments removed (4 ms)
    ✓ should call `new Promise()`
    ✓ `resolve()` should be called with a one argument (1 ms)
    ✓ `reject()` should be called with a one argument (1 ms)
    ✓ should resolve when the die settles successfully (2 ms)
    ✓ should reject with an Error when the die rolls off the table (2 ms)

  ● rollDie › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.146 s, estimated 11 s
Ran all test suites matching /ex3-rollDie.test.js/i.
2022-03-22 05:43:10 info: ---------------------------------------
2022-03-22 05:43:10 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-03-22 05:43:10 info: ---------------------------------------
2022-03-22 05:43:13 info: All unit tests passed.
2022-03-22 05:43:17 info: All steps were completed successfully
2022-03-22 06:25:58 info: ---------------------------------------
2022-03-22 06:25:58 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-03-22 06:25:58 info: ---------------------------------------
2022-03-22 06:26:03 info: All unit tests passed.
2022-03-22 06:26:09 error: *** Spell Checker Report ***

ex3-rollDie.js:57:18 - Unknown word (probelm)

2022-03-22 09:15:17 info: --------------------------------------------
2022-03-22 09:15:17 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-03-22 09:15:17 info: --------------------------------------------
2022-03-22 09:15:23 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    ✓ should exist and be executable (1 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✕ `rollDice` should not contain unneeded console.log calls (3 ms)
    ✓ should use `dice.map()`
    ✓ should use `Promise.all()` (1 ms)
    ✕ should resolve when all dice settle successfully (2 ms)
    ✓ should reject with an Error when a die rolls off the table (1 ms)

  ● ex4-pokerDiceAll › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● ex4-pokerDiceAll › `rollDice` should not contain unneeded console.log calls

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      137 |       });
      138 |
    > 139 |     expect(callsConsoleLog).toBe(false);
          |                             ^
      140 |   });
      141 | }
      142 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:139:29)

  ● ex4-pokerDiceAll › should resolve when all dice settle successfully

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise

    Received value has no prototype
    Received value: undefined

      52 |
      53 |     const promise = rollDice();
    > 54 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      55 |     const result = await promise;
      56 |     expect(Array.isArray(result)).toBe(true);
      57 |     expect(result).toHaveLength(5);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:54:21)

  ● ex4-pokerDiceAll › should resolve when all dice settle successfully

    expect.assertions(4)

    Expected four assertions to be called but received two assertion calls.

      46 |
      47 |   test('should resolve when all dice settle successfully', async () => {
    > 48 |     expect.assertions(4);
         |            ^
      49 |     expect(exported).toBeDefined();
      50 |
      51 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:48:12)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 4 passed, 7 total
Snapshots:   0 total
Time:        1.091 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Resolved! [ 'NINE', 'NINE', 'NINE', 'NINE', 'NINE' ]".

      32 |   const PromisesArray = dice.map((num) => {
      33 |     return rollDie(num);
    > 34 |   });
         |                ^
      35 |   Promise.all(PromisesArray)
      36 |     .then((results) => console.log('Resolved!', results))
      37 |     .catch((error) => console.log('Rejected!', error.message));

      at console.log (node_modules/@jest/console/build/CustomConsole.js:187:10)
      at 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js:34:54


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Rejected! Die 1 rolled off the table.
    ".

      32 |   const PromisesArray = dice.map((num) => {
      33 |     return rollDie(num);
    > 34 |   });
         |                ^
      35 |   Promise.all(PromisesArray)
      36 |     .then((results) => console.log('Resolved!', results))
      37 |     .catch((error) => console.log('Rejected!', error.message));

      at console.log (node_modules/@jest/console/build/CustomConsole.js:187:10)
      at 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js:34:104
2022-03-22 09:15:25 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  32:9  warning  Identifier 'PromisesArray' is not in camelCase  hyf/camelcase

✖ 1 problem (0 errors, 1 warning)


2022-03-22 09:26:57 info: --------------------------------------------
2022-03-22 09:26:57 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-03-22 09:26:57 info: --------------------------------------------
2022-03-22 09:27:03 info: All unit tests passed.
2022-03-22 09:27:05 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  31:9  warning  Identifier 'PromisesArray' is not in camelCase  hyf/camelcase

✖ 1 problem (0 errors, 1 warning)


2022-03-22 09:29:54 info: --------------------------------------------
2022-03-22 09:29:54 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-03-22 09:29:54 info: --------------------------------------------
2022-03-22 09:29:58 info: All unit tests passed.
2022-03-22 09:30:02 info: All steps were completed successfully
2022-03-22 09:38:18 info: ----------------------------------------------
2022-03-22 09:38:18 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2022-03-22 09:38:18 info: ----------------------------------------------
2022-03-22 09:38:24 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    ✓ should exist and be executable (1 ms)
    ✓ should have all TODO comments removed
    ✕ `rollDice` should not contain unneeded console.log calls (5 ms)
    ✓ should resolve when all dice settle successfully (30 ms)
    ✕ should reject with an Error when a die rolls off the table (33 ms)

  ● ex5-pokerDiceChain › `rollDice` should not contain unneeded console.log calls

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      137 |       });
      138 |
    > 139 |     expect(callsConsoleLog).toBe(false);
          |                             ^
      140 |   });
      141 | }
      142 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:139:29)

  ● ex5-pokerDiceChain › should reject with an Error when a die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      41 |
      42 |   test('should reject with an Error when a die rolls off the table', async () => {
    > 43 |     expect.assertions(3);
         |            ^
      44 |     expect(exported).toBeDefined();
      45 |
      46 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:43:12)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 3 passed, 5 total
Snapshots:   0 total
Time:        1.093 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.
2022-03-22 09:53:58 info: ----------------------------------------------
2022-03-22 09:53:58 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2022-03-22 09:53:58 info: ----------------------------------------------
2022-03-22 09:54:03 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    ✓ should exist and be executable (2 ms)
    ✓ should have all TODO comments removed (1 ms)
    ✓ `rollDice` should not contain unneeded console.log calls (2 ms)
    ✓ should resolve when all dice settle successfully (29 ms)
    ✕ should reject with an Error when a die rolls off the table (27 ms)

  ● ex5-pokerDiceChain › should reject with an Error when a die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      41 |
      42 |   test('should reject with an Error when a die rolls off the table', async () => {
    > 43 |     expect.assertions(3);
         |            ^
      44 |     expect(exported).toBeDefined();
      45 |
      46 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:43:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 passed, 5 total
Snapshots:   0 total
Time:        1.061 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.
2022-03-22 10:00:41 info: ----------------------------------------------
2022-03-22 10:00:41 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2022-03-22 10:00:41 info: ----------------------------------------------
2022-03-22 10:00:46 info: All unit tests passed.
2022-03-22 10:00:51 info: All steps were completed successfully
